name: Creating changes branch

on: 
    repository_dispatch:
        types: [user_changes]


#            mv -v ./appsAway/user_changes/* ./icub-tech-apps/dist/database/upgrade/
#            mv -v ./appsAway/user_changes/images/* ./icub-tech-apps/dist/express/images/

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: tibdex/github-app-token@v1
        with:
           private_key: ${{ secrets.ANOTHER_PRIVATE_KEY }}
           app_id: ${{ secrets.ANOTHER_APP_ID }}
           repository: my-organization-for-testing/human-sensing
           
      - uses: actions/checkout@v2
        env:
          GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}     
        with:
          repository: my-organization-for-testing/human-sensing
          token: ${{ env.GITHUB_APPS_TOKEN }}
          path: human-sensing
          ref: ${{ github.event.client_payload.branch_name }}
            
      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
            pr_title: "Adding user changes into the website."
            pr_body: "This is a test."
            pr_reviewer: "ilaria-carlini"
            pr_assignee: "lauracavaliere"
            source_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}
              
 
