name: Creating changes branch

on: 
    repository_dispatch:
        types: [user_changes]


#            mv -v ./appsAway/user_changes/* ./icub-tech-apps/dist/database/upgrade/
#            mv -v ./appsAway/user_changes/images/* ./icub-tech-apps/dist/express/images/

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:         
      - uses: actions/checkout@v2 
        with:
          repository: my-organization-for-testing/human-sensing
          token: ${{ secrets.MY_PAT }}
          
      - name: checking the directory content
        run: ls
            
      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
            pr_title: "Adding user changes into the website."
            pr_body: "This is a test."
            pr_reviewer: "ilaria-carlini"
            pr_assignee: "lauracavaliere"
            source_branch: "main"
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
              
 
